// Portfolios [Name, Role, Goal, Research, Users, Workflow, Wireframe,
//             Mockup, Prototype, Result, Figma, Conclusion, previous, next]
var food_ordering =  [ 
    'Food Ordering',
    'UI/UX Designer',
    'Our food ordering app aims to revolutionize the dining experience by streamlining the ordering process and addressing the critical issue of labor shortages in the restaurant industry. The primary objectives are to reduce wait times, enhance order accuracy, and improve overall customer satisfaction. By integrating advanced features such as real-time order tracking, AI-powered recommendations, and seamless payment options, we strive to create a more efficient and enjoyable dining experience for both customers and restaurant staff.',
    "To ensure our app effectively meets the needs of users and addresses industry challenges, we conducted comprehensive research, including:<ul><li><strong>Market Analysis</strong>: Evaluated current trends in the food ordering industry, identifying key pain points such as long wait times, order inaccuracies, and labor shortages. Our research revealed that 72% of customers prefer using apps for food ordering due to convenience and speed.</li><li><strong>Competitive Analysis</strong>: Analyzed leading food ordering apps to understand their strengths and weaknesses. Noted features such as user-friendly interfaces and loyalty programs that drive user retention.</li><li><strong>User Surveys</strong>: Collected feedback from over 500 potential users through online surveys to understand their preferences and pain points. Key findings showed that 85% of users value speed and accuracy, while 65% expressed frustration with current apps' complexity.</li><li><strong>Interviews</strong>: Conducted in-depth interviews with restaurant owners and staff to gain insights into operational challenges and potential solutions. Highlighted issues such as staff shortages, high turnover rates, and the need for efficient order management systems.</li></ul>",
    'Our primary users include:<ul><li><strong>Customers</strong>: Individuals aged 18-45 who frequently order food online due to convenience, busy lifestyles, and a preference for quick service. Data shows that 60% of our target audience orders food online at least once a week.</li><li><strong>Restaurant Staff</strong>: Employees and managers who require efficient tools to manage orders, reduce errors, and handle high volumes during peak hours. Feedback from 50 restaurant staff members emphasized the need for a user-friendly order management system.</li><li><strong>Restaurant Owners</strong>: Business owners who aim to optimize operations, reduce labor costs, and enhance customer satisfaction. Survey results indicated that 70% of restaurant owners are willing to invest in technology that addresses labor shortages and improves service efficiency.</li></ul>',
    'Food Ordering workflow',
    'Food Ordering wireframe',
    'QuickClick',
    'Food Ordering prototype',
    "We conducted usability studies with 30 participants to evaluate the app's design and functionality. Key findings include:</p><ul><li><strong>Task Completion Rates</strong>: 95% of participants successfully placed an order within 3 minutes, significantly reducing the average time compared to existing apps.</li><li><strong>Error Rates</strong>: The app's intuitive design led to a 40% reduction in order errors, enhancing accuracy and customer satisfaction.</li><li><strong>User Satisfaction</strong>: 88% of participants rated their experience as 'excellent' or 'very good', highlighting the app's ease of use and efficiency.</li><li><strong>Feature Utilization</strong>: AI-powered recommendations were utilized by 60% of users, leading to a 15% increase in average order value.</li></ul>",
    'Contact us for complete Figma design',
    "Our research and usability studies underscore the importance of a user-centric approach in designing a food ordering app. By addressing key pain points such as wait times, order inaccuracies, and labor shortages, our app enhances the overall dining experience for customers and streamlines operations for restaurant staff.<br>Key takeaways include:<ul><li><strong>User-Centric Design</strong>: Prioritizing ease of use and intuitive navigation significantly improves user satisfaction and reduces error rates.</li><li><strong>Efficiency</strong>: Implementing features like real-time tracking and AI recommendations not only enhances the user experience but also boosts operational efficiency and revenue.</li><li><strong>Scalability</strong>: The app's design and functionality are scalable, making it suitable for various types of restaurants, from small cafes to large chains.</li></ul>In conclusion, our food ordering app successfully addresses the critical needs of both customers and the restaurant industry. By leveraging technology and user-centered design principles, we have created a solution that enhances the food ordering experience and tackles the pressing issue of labor shortages.",
    '',
    'payment_hub' ];
var payment_hub =  [ 
    'Payment Hub',
    'UI/UX Designer',
    'Our food ordering app aims to revolutionize the dining experience by streamlining the ordering process and addressing the critical issue of labor shortages in the restaurant industry. The primary objectives are to reduce wait times, enhance order accuracy, and improve overall customer satisfaction. By integrating advanced features such as real-time order tracking, AI-powered recommendations, and seamless payment options, we strive to create a more efficient and enjoyable dining experience for both customers and restaurant staff.',
    "To ensure our app effectively meets the needs of users and addresses industry challenges, we conducted comprehensive research, including:<ul><li><strong>Market Analysis</strong>: Evaluated current trends in the food ordering industry, identifying key pain points such as long wait times, order inaccuracies, and labor shortages. Our research revealed that 72% of customers prefer using apps for food ordering due to convenience and speed.</li><li><strong>Competitive Analysis</strong>: Analyzed leading food ordering apps to understand their strengths and weaknesses. Noted features such as user-friendly interfaces and loyalty programs that drive user retention.</li><li><strong>User Surveys</strong>: Collected feedback from over 500 potential users through online surveys to understand their preferences and pain points. Key findings showed that 85% of users value speed and accuracy, while 65% expressed frustration with current apps' complexity.</li><li><strong>Interviews</strong>: Conducted in-depth interviews with restaurant owners and staff to gain insights into operational challenges and potential solutions. Highlighted issues such as staff shortages, high turnover rates, and the need for efficient order management systems.</li></ul>",
    'Our primary users include:<ul><li><strong>Customers</strong>: Individuals aged 18-45 who frequently order food online due to convenience, busy lifestyles, and a preference for quick service. Data shows that 60% of our target audience orders food online at least once a week.</li><li><strong>Restaurant Staff</strong>: Employees and managers who require efficient tools to manage orders, reduce errors, and handle high volumes during peak hours. Feedback from 50 restaurant staff members emphasized the need for a user-friendly order management system.</li><li><strong>Restaurant Owners</strong>: Business owners who aim to optimize operations, reduce labor costs, and enhance customer satisfaction. Survey results indicated that 70% of restaurant owners are willing to invest in technology that addresses labor shortages and improves service efficiency.</li></ul>',
    'Payment Hub workflow',
    'Payment Hub wireframe',
    'Pay',
    'Payment Hub prototype',
    "We conducted usability studies with 30 participants to evaluate the app's design and functionality. Key findings include:<ul><li><strong>Task Completion Rates</strong>: 95% of participants successfully placed an order within 3 minutes, significantly reducing the average time compared to existing apps.</li><li><strong>Error Rates</strong>: The app's intuitive design led to a 40% reduction in order errors, enhancing accuracy and customer satisfaction.</li><li><strong>User Satisfaction</strong>: 88% of participants rated their experience as 'excellent' or 'very good', highlighting the app's ease of use and efficiency.</li><li><strong>Feature Utilization</strong>: AI-powered recommendations were utilized by 60% of users, leading to a 15% increase in average order value.</li></ul>",
    'Contact us for complete Figma design',
    "Our research and usability studies underscore the importance of a user-centric approach in designing a food ordering app. By addressing key pain points such as wait times, order inaccuracies, and labor shortages, our app enhances the overall dining experience for customers and streamlines operations for restaurant staff.<br>Key takeaways include:<ul><li><strong>User-Centric Design</strong>: Prioritizing ease of use and intuitive navigation significantly improves user satisfaction and reduces error rates.</li><li><strong>Efficiency</strong>: Implementing features like real-time tracking and AI recommendations not only enhances the user experience but also boosts operational efficiency and revenue.</li><li><strong>Scalability</strong>: The app's design and functionality are scalable, making it suitable for various types of restaurants, from small cafes to large chains.</li></ul>In conclusion, our food ordering app successfully addresses the critical needs of both customers and the restaurant industry. By leveraging technology and user-centered design principles, we have created a solution that enhances the food ordering experience and tackles the pressing issue of labor shortages.",
    'food_ordering',
    'coupon_app' ];
var coupon_app =  [ 
    'Coupon App',
    'Product Designer',
    'Our Coupon App is designed to promote local tourism by offering exclusive discounts and deals to tourists. By partnering with local businesses and government agencies, the app aims to attract more visitors, boost local economy, and provide tourists with a more affordable and enjoyable experience. Key objectives include increasing tourist engagement, driving traffic to local attractions and businesses, and enhancing the overall tourist experience.',
    'To ensure the effectiveness of our Coupon App, we conducted extensive research, including:<ul><li><strong>Market Analysis</strong>: Examined tourism trends and the impact of discounts on tourist behavior. Our research revealed that 75% of tourists are more likely to visit a destination if they can access discounts and deals.</li><li><strong>Competitive Analysis</strong>: Analyzed existing coupon and tourism apps to identify strengths and weaknesses. Noted that 60% of users prefer apps that offer a wide range of local deals and easy redemption processes.</li><li><strong>User Surveys</strong>: Collected feedback from over 600 potential users through online surveys. Key findings showed that 80% of respondents would use an app that provides localized discounts, and 70% were interested in deals on dining and entertainment.</li><li><strong>Interviews</strong>: Conducted in-depth interviews with 50 tourists and 30 local business owners. Tourists emphasized the importance of easy-to-find and redeemable coupons, while business owners highlighted the need for a platform that effectively promotes their services.</li></ul>',
    'Our primary users include:<ul><li><strong>Tourists</strong>: Individuals and families visiting local destinations who seek to save money on attractions, dining, and shopping. Survey data indicated that 85% of tourists look for discounts before traveling.</li><li><strong>Local Businesses</strong>: Restaurants, shops, and entertainment venues that want to attract more customers through targeted promotions. Interviews with business owners revealed that 65% were willing to offer discounts in exchange for increased visibility.</li><li><strong>Local Government and Tourism Boards</strong>: Entities focused on boosting local tourism and supporting the economy. Feedback from local government officials showed strong support for initiatives that drive tourist traffic and spending.</li></ul>',
    'Coupon App workflow',
    'Coupon App wireframe',
    'Taoyuan Point',
    'Coupon App prototype',
    "We conducted usability studies with 40 participants to evaluate the app's design and functionality. Key findings include:<ul><li><strong>Task Completion Rates</strong>: 90% of participants successfully found and redeemed a coupon within 3 minutes, demonstrating the app's user-friendly interface.</li><li><strong>User Satisfaction</strong>: 87% of participants rated their experience as 'excellent' or 'very good', citing the ease of finding relevant deals and the straightforward redemption process.</li><li><strong>Error Rates</strong>: The app's intuitive design led to a 30% reduction in user errors compared to similar apps, enhancing overall satisfaction.</li><li><strong>Feature Utilization</strong>: The location-based deal finder was utilized by 75% of users, indicating strong interest in nearby discounts and promotions.</li></ul>",
    'Contact us for complete Figma design',
    'Our research and usability studies highlight the importance of a user-centric approach in designing a Coupon App. By focusing on ease of use, relevant deals, and seamless redemption processes, we have created a solution that benefits tourists, local businesses, and government agencies alike.<br>Key takeaways include:<ul><li><strong>Relevance</strong>: Offering localized and easily redeemable coupons significantly increases user engagement and satisfaction.</li><li><strong>User-Friendly Design</strong>: A straightforward interface and efficient navigation enhance task completion rates and reduce errors.</li><li><strong>Collaboration</strong>: Partnering with local businesses and government entities is crucial for providing valuable deals and promoting tourism effectively.</li></ul>In conclusion, our Coupon App successfully addresses the needs of tourists seeking discounts and local businesses aiming to attract more customers. By leveraging comprehensive research and focusing on user needs, we have developed a solution that supports local tourism, boosts the economy, and provides an enhanced experience for visitors.',
    'payment_hub',
    '' ];

window.onload = () => {
    const project = new URLSearchParams(window.location.search).get('project');
    document.getElementById("name").innerHTML       = eval(project)[0];
    document.getElementById("bg").src               = 'img/research/' + eval(project)[0] + '.png';
    document.getElementById("role").innerHTML       = eval(project)[1];
    document.getElementById("goal").innerHTML       = eval(project)[2];
    document.getElementById("search").innerHTML     = eval(project)[3];
    document.getElementById("users").innerHTML      = eval(project)[4];
    document.getElementById("workflow").src         = 'img/research/' + eval(project)[5] + '.png';
    document.getElementById("wireframe").src        = 'img/research/' + eval(project)[6] + '.png';
    document.getElementById("mockup").src           = 'img/portfolio/' + eval(project)[7] + '.png';
    document.getElementById("prototype").src        = 'img/research/' + eval(project)[8] + '.png';
    document.getElementById("result").innerHTML     = eval(project)[9];
    document.getElementById("figma").innerHTML      = eval(project)[10];
    document.getElementById("conclusion").innerHTML = eval(project)[11];
    if (eval(project)[12]) {
        document.getElementById("previous").href = 'research.html?project=' + eval(project)[12];
        document.querySelectorAll('#previous span')[0].innerHTML = eval(eval(project)[12])[0]; }
    else
        document.getElementById("previous").classList.add('disabled');
    if (eval(project)[13]) {
        document.getElementById("next").href = 'research.html?project=' + eval(project)[13];
        document.querySelectorAll('#next span')[0].innerHTML = eval(eval(project)[13])[0]; }
    else
        document.getElementById("next").classList.add('disabled'); };